apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
  - path: application_gh_cloudify_waec_service.yaml
    target:
    kind: Deployment
    strategicMergePatch:
      spec:
        replicas: 3
        # template:
        #   spec:
        #     containers:
        #       image: 842092678711.dkr.ecr.eu-west-1.amazonaws.com/gh-cloudify-waec-service:release-1.0.0-SNAPSHOT-1


