apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# patches:
#   - path: ../../base/application_gh_cloudify_waec_service.yaml
#     target:
#       kind: Deployment
#       name: gh-cloudify-waec
#   - patch: |
#       - op: replace
#         path: /spec/replicas
#         value: 3